version: "3"
services:
  app:
    container_name: react-app
    image: docker-react
    build:
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true
